### ISSUE TITLE
Create a NHVerify.Scraper protocol and use &Protocol.extract_impls/2 in tests

### ISSUE THREAD

**Issue by Eiji7** [jeffdeville/nhverify#4]
From Google Hangouts chat we decided to make an easy to test `Protocol` that **all scrapers needs** to implement.
This protocol will have one public API that would be used in tests when iterating over protocol implementations, see: [&Protocol.extract_impls/2](http://elixir-lang.org/docs/stable/elixir/Protocol.html#extract_impls/2).

**TODO**:
- [ ] Create `NHVerify.Scraper` protocol
- [ ] Change already created scrapers (modules) to much new protocol implementation
- [ ] Add tests for new protocol

**Comment by jeffdeville** [comment]
How will Protocols work in this instance?  They require a 'for' parameter that corresponds to a Type, but in this case, I don't know what that type would be. Also, I was under the impression that behaviours were the preferred mechanism when you're dealing with your own code. Protocols when you were going to have it extended by others for their use.  

As a result, I created: https://github.com/jeffdeville/nhverify/blob/master/lib/nh_verify/producer.ex

I like the protocols can be automatically scanned, but I think that so long as every scraper is in the producers folder, we should be able to load each file up and assume each one contains a producer.

**Comment by Eiji7** [comment]
@jeffdeville: We can simply create struct with no data.
Simple example in iex:
```elixir
defprotocol Example.SampleProtocol, do: nil
defmodule Example.Producers.First, do: defstruct []
defimpl Example.SampleProtocol, for: Example.Producers.First, do: nil
path = :code.lib_dir(:example, :ebin)
mods = Protocol.extract_impls(Example.SampleProtocol, [path])
# returns: [Example.Producers.First]
```
Then we need iterate them and create structs, by `[&Kernel.struct/2](http://elixir-lang.org/docs/stable/elixir/Kernel.html#struct/2) and finally pass each struct to protocol method as first argument.
